app:
  name: Vim/NeoVim
  link: https://neovim.io/
type: editor
beta: true
external:
  link: https://github.com/base9-theme/base9-vim
installation:
- copy_palette: true
  before_md: |
    Install https://github.com/base9-theme/base9-vim
    using your favorite plugin manager

  after_md: |
    Set palette and set colorscheme to `base9`.

    ```
    let g:base9_palette = '000000-111111-222222-333333-444444-555555-666666-777777-888888'
    colorscheme base9
    ```

