app:
  name: WezTerm
  link: https://wezfurlong.org/wezterm
type: terminal
installation:
- write_template: true
  template: default.toml.mustache
  destination: ~/.config/wezterm/colors/Base9.toml
  before_md: |
    Make sure wezterm [config](https://wezfurlong.org/wezterm/config/files.html)
    has color_scheme set to `Base9`:
    ```lua
    return {
      -- ...
      color_scheme: 'Base9',
      -- ...
    }
    ```
  after_md: ""

