name: Base9 Wezterm
key: wezterm # has to be the same as folder name
app:
  name: WezTerm
  link: https://wezfurlong.org/wezterm
# screenshot: # optional
#   palettes:
#     - "282828-ebdbb2-83a598-8ec07c-fe8019-fabd2f-b8bb26-d3869b-fb4934"
#   prefix: "./screenshots/Screenshot_"
#   extension: ".png"
platforms:
  - name: Linux
    template: default.toml.mustache
    destination: ~/.config/wezterm/colors/Base9.toml
    setup_md: | # optional
      Make sure wezterm has color_scheme set to `Base9`:
      ```lua
      return {
        -- ...
        color_scheme: 'Base9',
        -- ...
      }
      ```

