name: Base9 Alacritty
key: alacritty # has to be the same as folder name
app:
  name: Alacritty
  link: https://github.com/alacritty/alacritty
screenshot: # optional
  palettes:
    - "282828-ebdbb2-83a598-8ec07c-fe8019-fabd2f-b8bb26-d3869b-fb4934"
  prefix: "./screenshots/Screenshot_"
  extension: ".png"
platforms:
  - name: Linux
    template: default.yml.mustache
    destination: ~/.config/alacritty/themes/base9.yml
    setup_md: | # optional
      Make sure `~/.config/alacritty/alacritty.yml` has the following:
      ```yaml
      import:
        - '~/.config/alacritty/themes/base9.yml'
      ```

