app:
  name: Alacritty
  link: https://github.com/alacritty/alacritty
type: terminal
screenshots:
- title: "282828-ebdbb2-83a598-8ec07c-fe8019-fabd2f-b8bb26-d3869b-fb4934"
  link: "https://user-images.githubusercontent.com/2196866/180703789-8fa6c00a-e91f-4e69-ab8e-8d0084da9dd0.png"
installation:
- writeTemplate: true
  template: alacritty/default.yml.mustache
  destination: ~/.config/alacritty/base9.yml

  before_md: | # put at the very begining of the installation section
    Make sure `~/.config/alacritty/alacritty.yml` has the following:
    ```yaml
    import:
      - '~/.config/alacritty/base9.yml'
    ```
  after_md: "" # put at the very end of the installation section
