/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
  /**
   * info related to the app itself
   */
  app: {
    /**
     * Name of the app
     */
    name: string;
    /**
     * official link of the app
     */
    link: string;
    [k: string]: unknown;
  };
  /**
   * `terminal`: if the app is a terminal emulator
   * `editor`: if the app is a code editor
   * `gui`: if the app is a general desktop app, a desktop environment, or a window manager
   * `library`: if the app is a library.
   *
   */
  type: string;
  external?: {
    /**
     * link to the actual template repo
     */
    link: string;
    [k: string]: unknown;
  };
  /**
   * true if the theme is not super polished and needs contributions.
   */
  beta?: true;
  screenshots?: {
    title: string;
    link: string;
    [k: string]: unknown;
  }[];
  /**
   * @minItems 1
   */
  installation: [
    (
      | {
          /**
           * true if install requires copying palette to somewhere
           */
          copy_palette: true;
          [k: string]: unknown;
        }
      | {
          /**
           * true if install requires writing generated template to some file
           */
          write_template: true;
          /**
           * path relative to the template folder
           */
          template: string;
          /**
           * path of the file to write template to
           */
          destination: string;
          [k: string]: unknown;
        }
      | {
          /**
           * true if install requires copying generated template to somewhere
           */
          copy_template: true;
          /**
           * path relative to the template folder
           */
          template: string;
          [k: string]: unknown;
        }
    ),
    ...(
      | {
          /**
           * true if install requires copying palette to somewhere
           */
          copy_palette: true;
          [k: string]: unknown;
        }
      | {
          /**
           * true if install requires writing generated template to some file
           */
          write_template: true;
          /**
           * path relative to the template folder
           */
          template: string;
          /**
           * path of the file to write template to
           */
          destination: string;
          [k: string]: unknown;
        }
      | {
          /**
           * true if install requires copying generated template to somewhere
           */
          copy_template: true;
          /**
           * path relative to the template folder
           */
          template: string;
          [k: string]: unknown;
        }
    )[]
  ];
}
